# Generated by Django 4.1.1 on 2022-09-16 21:57

from django.db import migrations, models
import litsource.models


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litsource',
            name='source_type',
        ),
        migrations.AddField(
            model_name='litsource',
            name='bibtexdata',
            field=models.CharField(default='', help_text='Полное название источника будет использовано при формировании pdf отчета - (например Приказ Министерства природных ресурсов и экологии РФ от 4 декабря 2014 г. N 536 "Об утверждении Критериев отнесения отходов к I-V классам опасности по степени негативного воздействия на окружающую среду")', max_length=2000, unique=True, validators=[litsource.models.validate_bibtex], verbose_name='Строка bibtex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='litsource',
            name='fullname',
            field=models.CharField(default='', help_text='Полное название источника будет использовано при формировании pdf отчета - (например Приказ Министерства природных ресурсов и экологии РФ от 4 декабря 2014 г. N 536 "Об утверждении Критериев отнесения отходов к I-V классам опасности по степени негативного воздействия на окружающую среду")', max_length=500, unique=True, verbose_name='Полное название источника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litsource',
            name='name',
            field=models.CharField(help_text='Название источника будет показано на вебстранице рядом со свойством - можно указать короткое название (например Приказ Минприроды N 536)', max_length=200, unique=True, verbose_name='Название источника'),
        ),
    ]
