# Generated by Django 4.1.1 on 2022-09-16 23:49

from django.db import migrations, models
import litsource.models


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0002_remove_litsource_source_type_litsource_bibtexdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litsource',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='litsource',
            name='bibtexdata',
            field=models.TextField(help_text='Укажите ссылку на документ в формате bibtex. После сохранения тэг статьи будет изменен на уникальный. Например: @article{dmitrievgost,\n                    title={ГОСТ ГОСТу-рознь},\n                    author={Дмитриев, Евгений Аристархович},\n                    journal={Гражданская защита}\n                    }', max_length=2000, validators=[litsource.models.validate_bibtex], verbose_name='Строка bibtex'),
        ),
    ]
