# Generated by Django 4.1.1 on 2022-09-18 20:36

from django.db import migrations, models
import litsource.models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LitSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название источника будет показано на вебстранице рядом со свойством - можно указать короткое название (например Приказ Минприроды N 536)', max_length=200, unique=True, verbose_name='Название источника')),
                ('bibtexdata', models.TextField(help_text='Укажите ссылку на документ в формате bibtex. После сохранения тэг статьи будет изменен на уникальный. Например: @article{dmitrievgost,\n                    title={ГОСТ ГОСТу-рознь},\n                    author={Дмитриев, Евгений Аристархович},\n                    journal={Гражданская защита}\n                    }', max_length=2000, validators=[litsource.models.validate_bibtex], verbose_name='Строка bibtex')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Url cсылка на источник (при наличии)')),
            ],
            options={
                'verbose_name': 'Источник литературы',
                'verbose_name_plural': 'Источники литературы',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
