# Generated by Django 4.0.3 on 2022-04-10 10:13

from django.db import migrations, models
import django.db.models.deletion
import litsource.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('props', wagtail.core.fields.StreamField([('PDKp', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, required=True))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
