# Generated by Django 4.0.3 on 2022-04-12 15:47

from django.db import migrations
import litsource.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0002_substance_ldprops_alter_substance_airprops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='foodprops',
            field=wagtail.core.fields.StreamField([('pdkpp', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Предельно допустимая концентрация вещества в пищевых продуктах [мг/кг]', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('mds', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Максимально допустимое содержание [мг/кг]', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('mdu', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Максимально допустимый уровень [мг/кг]', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='props',
            field=wagtail.core.fields.StreamField([('Kow', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Коэффициент распределения в системе октанол/вода при 20° C', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('Solubility', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Растворимость компонента отхода (вещества) в воде при 20° C', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('COD', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Химическое потребление кислорода, выраженное в миллилитрах O2/100 л', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('BOD5', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Биологическое потребление кислорода, выраженное в миллилитрах O2/л за 5 суток', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))])), ('Cnas', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.FloatBlock(label='Насыщающая концентрация вещества в воздухе при 20° C и нормальном давлении [мг/м3]', min_value=0, required=True)), ('source', wagtail.snippets.blocks.SnippetChooserBlock(litsource.models.LitSource, label='Источник литературы для значения', required=True))]))], blank=True, null=True),
        ),
    ]
