# Generated by Django 4.0.3 on 2022-04-13 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0002_alter_litsource_options_litsource_source_type_and_more'),
        ('substance', '0003_substance_foodprops_substance_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='x_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='X - относительный параметр опасности компонента отхода для окружающей среды (если известен - указание источника обязательно)'),
        ),
        migrations.AddField(
            model_name='substance',
            name='x_value_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='x_value', to='litsource.litsource', verbose_name='Источник литературы для относительного параметра опаности (если задано числовое значение X, то обязателен)'),
        ),
    ]
