# Generated by Django 4.0.3 on 2022-04-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0004_substance_x_value_substance_x_value_lit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='cas_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='CAS код для вещества в формате 1111-11-1', regex='\\b[1-9]{1}[0-9]{1,6}-\\d{2}-\\d\\b')], verbose_name='Регистрационный номер CAS'),
        ),
        migrations.AddField(
            model_name='substance',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Другие названия (через точку с запятой)'),
        ),
    ]
